### ISSUE TITLE
should have better error handling when api key missing

### ISSUE THREAD

**Issue by 7flash** [togethercomputer/together-cli#3]
Currently script missing API key
```
python3 -c '''
import together

file_resp = together.Files.upload(file="Jan30-1654.jsonl")
file_id = file_resp["id"]
print(file_id)
```

 gives following error

```
01-30-2024 18:12:20 - together.files - CRITICAL - Unexpected error raised by endpoint. Response status code: 403 (files.py:102)
01-30-2024 18:12:20 - together.files - CRITICAL - Response error raised: Unexpected error raised by endpoint. (files.py:144)
Traceback (most recent call last):
  File "/Users/gur/miniconda3/lib/python3.11/site-packages/together/files.py", line 105, in upload
    raise together.ResponseError(
together.error.ResponseError: Unexpected error raised by endpoint.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/Users/gur/miniconda3/lib/python3.11/site-packages/together/files.py", line 145, in upload
    raise together.ResponseError(e)
together.error.ResponseError: Unexpected error raised by endpoint.
```

The same with CLI command 

```
together files upload Jan30-1654.jsonl
```

This CLI error is fixed by

```
export TOGETHER_API_KEY=""
```

and correspondingly updated script works:

```
python3 -c '''
import os
import together

together.api_key = os.environ["TOGETHER_API_KEY"];

file_resp = together.Files.upload(file="Jan30-1654.jsonl")
file_id = file_resp["id"]
print(file_id)
'''
```

I think original error message should be updated otherwise it's not clear that it can be solved by export TOGETHER_API_KEY

**Comment by 7flash** [comment]
```
if "TOGETHER_API_KEY" not in os.environ:
    raise ValueError("TOGETHER_API_KEY environment variable is not defined")
```
